# Site settings
title: Stavros Foteinopoulos - Senior Site Reliability Engineer
description: "Senior Site Reliability Engineer focused on cloud infrastructure and FinOps"
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "http://stafot.github.io"
# User settings
username: stafot
user_title: Senior Site Reliability Engineer II
email: stafot@gmail.com
#twitter_username: loremipsum
github_username: stafot
gplus_username: 117203916724467570699
linkedin_public_url: stafot # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: loremipsum
profile_picture: https://avatars0.githubusercontent.com/u/2853082?s=400&u=4ae924ca30ec2631de243c8dddb0a7b9bb1e8fae&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
#  - title: series
#    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about

# projects in header index
projects:
  - name: Kubernetes Node Local DNS Cache Service
    url: https://github.com/kubernetes/kubernetes/pull/88412
  - name: Ingress NGINX Controller Improvements
    url: https://github.com/kubernetes/ingress-nginx/pull/10731
  - name: Prometheus Operator Enhancements
    url: https://github.com/prometheus-operator/prometheus-operator/pull/3899
  - name: Prometheus Community Charts - Kube Prometheus Stack
    url: https://github.com/prometheus-community/helm-charts/pull/639
  - name: Prometheus Community Charts - Node Exporter
    url: https://github.com/prometheus-community/helm-charts/pull/641
  - name: Prometheus Community Charts - Alertmanager
    url: https://github.com/prometheus-community/helm-charts/pull/644

# Mentoring and Community
mentoring:
  - role: Technical Mentor at Tupu.io
    period: Apr 2022 - Feb 2023
    description: Mentored underrepresented minorities in tech, focusing on SRE, Cloud, and DevOps practices
  - role: Technical Advisor
    description: Provided guidance on cloud-native transformations and infrastructure modernization

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']